server:
    port: 8081
    servlet:
        context-path: /demo
spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3307/wp
        username: root
        password: pass
        driverClassName: com.mysql.cj.jdbc.Driver
mybatis:
    type-aliases-package: com.drools.model
    type-handlers-package: com.drools.dao
    configuration:
        map-underscore-to-camel-case: true
        default-fetch-size: 100
        default-statement-timeout: 30